
package com.ddsoft.translate.gui;

import com.ddsoft.translate.classes.MyFont;
import com.ddsoft.translate.classes.SaveToFile;
import com.ddsoft.translate.classes.TranslaterLogic;
import java.awt.Font;
import javax.swing.JOptionPane;


/**
 *
 * @author kam
 */
public class TranslaterInterface extends javax.swing.JFrame {

    private TranslaterLogic workin;
    /**
     * Creates new form TranslaterInterface
     */
    public TranslaterInterface() {
        initComponents();
        workin=new TranslaterLogic();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfAbout = new javax.swing.JFrame();
        btnjfClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblVer = new javax.swing.JLabel();
        lblBG = new javax.swing.JLabel();
        jfHelp = new javax.swing.JFrame();
        lblHelpImg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBox1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBox2 = new javax.swing.JTextArea();
        btnReset = new javax.swing.JButton();
        btnCopy = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmenuSave = new javax.swing.JMenuItem();
        jmenuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmemuHelp = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jfAbout.setTitle("About");
        jfAbout.setBounds(new java.awt.Rectangle(0, 0, 650, 445));
        jfAbout.setResizable(false);
        jfAbout.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnjfClose.setText("Close");
        btnjfClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjfCloseActionPerformed(evt);
            }
        });
        jfAbout.getContentPane().add(btnjfClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Singlish Translater");
        jfAbout.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 160, -1));

        lblVer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVer.setForeground(new java.awt.Color(255, 255, 255));
        lblVer.setText("0.1");
        jfAbout.getContentPane().add(lblVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 40, -1));

        lblBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ddsoft/translate/image/logodesign.jpg"))); // NOI18N
        jfAbout.getContentPane().add(lblBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        jfHelp.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jfHelp.setTitle("Help");
        jfHelp.setBounds(new java.awt.Rectangle(0, 0, 893, 640));
        jfHelp.setResizable(false);

        lblHelpImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ddsoft/translate/image/help.jpg"))); // NOI18N

        javax.swing.GroupLayout jfHelpLayout = new javax.swing.GroupLayout(jfHelp.getContentPane());
        jfHelp.getContentPane().setLayout(jfHelpLayout);
        jfHelpLayout.setHorizontalGroup(
            jfHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHelpImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jfHelpLayout.setVerticalGroup(
            jfHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHelpImg, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Singlish Translater");

        txtBox1.setColumns(20);
        txtBox1.setRows(7);
        txtBox1.setToolTipText("Type in singlish");
        txtBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBox1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtBox1);

        txtBox2.setColumns(20);
        txtBox2.setRows(5);
        jScrollPane2.setViewportView(txtBox2);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnCopy.setText("Copy");
        btnCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jmenuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmenuSave.setText("Save to File");
        jmenuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuSaveActionPerformed(evt);
            }
        });
        jMenu1.add(jmenuSave);

        jmenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jmenuExit.setText("Exit");
        jmenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuExitActionPerformed(evt);
            }
        });
        jMenu1.add(jmenuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jmemuHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jmemuHelp.setText("Help");
        jmemuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmemuHelpActionPerformed(evt);
            }
        });
        jMenu2.add(jmemuHelp);

        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnReset)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCopy)
                                .addGap(19, 19, 19))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCopy)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       txtBox1.setText("");
       txtBox2.setText("");
       System.gc();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyActionPerformed

        txtBox2.selectAll();
        txtBox2.copy();
        
    }//GEN-LAST:event_btnCopyActionPerformed

    private void txtBox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBox1KeyReleased
convertion();
    }//GEN-LAST:event_txtBox1KeyReleased

    private void jmenuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuSaveActionPerformed
        
      SaveToFile.saveFile(txtBox2.getText());
        
    }//GEN-LAST:event_jmenuSaveActionPerformed

    private void jmemuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmemuHelpActionPerformed
        jfHelp.setVisible(true);
    }//GEN-LAST:event_jmemuHelpActionPerformed

    private void btnjfCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjfCloseActionPerformed
       jfAbout.dispose();
    }//GEN-LAST:event_btnjfCloseActionPerformed

    private void jmenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuExitActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_jmenuExitActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       jfAbout.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * The Singlish to Sinhala Unicode translation handling place
     */
    private void convertion(){
          txtBox2.setText(workin.convertText(txtBox1.getText())) ;        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
              
        MyFont.setUIFont(new javax.swing.plaf.FontUIResource("Iskoola pota",Font.PLAIN,18));
        new TranslaterInterface().setVisible(true); 
     
        
        
        
      /*
       * to do since there is only one therad running both ui and logic it might be a good idea to run in seperate threads
       */
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopy;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnjfClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFrame jfAbout;
    private javax.swing.JFrame jfHelp;
    private javax.swing.JMenuItem jmemuHelp;
    private javax.swing.JMenuItem jmenuExit;
    private javax.swing.JMenuItem jmenuSave;
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblHelpImg;
    private javax.swing.JLabel lblVer;
    private javax.swing.JTextArea txtBox1;
    private javax.swing.JTextArea txtBox2;
    // End of variables declaration//GEN-END:variables
}
